---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.7.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .poetry.lock
          cache: poetry

      - name: Install dependencies
        run: make install-dev

      - name: Lint Python
        run: make lint

      - name: Format Python
        run: make format
      
      - name: Cleanup residue file
        run: make clean